### ISSUE TITLE
do not use use repo.

### ISSUE THREAD

**Issue by morandd** [msrocka/soda-df#1]
Wasted several hours on this before seeing there's an official up-to-date docker compose file:

https://bitbucket.org/okusche/soda4lca/src/7.12.0/Doc/src/Installation_Guide/Installation_Guide.md

This dockerfile in September 2024 does not work out of the box due to many broken download links.

**Comment by msrocka** [comment]
yes, of course, you should use the official images now, which were not available when I created this 7 years ago...; I will add a note an archive this repository
